<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Simple Cloud API</title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
<link href="/css/grid-960/styles/reset.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/css/grid-960/styles/text.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/css/grid-960/styles/960.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/style.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/nav.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/blog.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/forum.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/search.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/skins.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/form.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/feed.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/home.css" media="screen"
	rel="stylesheet" type="text/css">
<link href="/templates/public/scapi/css/sitemap.css" media="screen"
	rel="stylesheet" type="text/css">
</head>        

<body class='default'>
    <div class='container_12'>
        <div id='header' class='container_12'>
        	<div id='top'>
        		<div style="display: block; float: right; height: 60px; width: 60px;"></div>
        		<div class='grid_4 alpha' id='logoWrapper'><a href='/' id='logo'></a></div>
        	</div>
            <div class='grid_8 omega' id='pageQuote'>
            	<blockquote>
            		<div id="quote">
            			<span id="quoteBody" class='quoteBody'>
                			Einmal schreiben, in jeder Cloud deployen - Einblick in Simple Cloud
                		</span> 
                		<span id="quoteCredit" class='quoteCredit'>
                			Zend Technologies
                		</span>
                	</div>
            	</blockquote>
            </div>
        
        	<div class='clear'></div>
        
            <div id="navigationWrapper" class='grid_9 alpha'>
                <ul class="navigation">
                	<li><a href="/" id="menu-home">HOME</a></li>
                	<li><a href="/storage" id="menu-api">STORAGE</a></li>
                	<li><a href="/queue" id="menu-blog">QUEUE</a></li>
                	<li><a href="/document" id="menu-forum">DOCUMENT</a></li>
                </ul>
            </div>
        </div>
        
        <div class='clear'></div>
        
        <div id='pageBody' class='container_12'>
        	<div class='grid_3 alpha' id='sidebar'>
        		<div class='innerContent'>
        
       				<div class='feedBody'></div>
        			<p class="footnote">&nbsp;</p>
        		</div>
       	 	</div>
        	<div class='grid_9 omega'>
        		<div class='innerContent'>
        			<div class="home-text grid_6 alpha">
        				<?php echo $this->layout()->content ?>
                	</div>
        			<div class="contributors grid_3 omega">
        				<p></p>
        			</div>
        
        		</div>
        	</div>
    	</div>
	</div>
</body>
</html>