<table class="compat-table">
	<thead>
		<tr>
			<td class="compat-table-header">FileName</td>
			<td class="compat-table-header">&nbsp;</td>
		</tr>
	</thead>
	<tbody>
        <tr>
        	<td style="padding: 10px; vertical-align: top; border-right: 1px solid black;"><?php echo $this->writeForm ?></td>
            <td style="padding: 10px; vertical-align: top;"><?php echo $this->readForm ?></td>
        </tr>
	</tbody>
</table>
<?php if ($this->messageWrite) :?>
<p style="padding: 10px;">Message erfolgreich geschrieben!</p>
<?php endif; ?>
<?php if ($this->nothingToRead) :?>
<p style="padding: 10px;">Keine Nachrichten in Queue!</p>
<?php endif; ?>