<p>The Simple Cloud API brings cloud technologies to PHP and the
PHPilosophy to the cloud, starting with common interfaces for three
cloud application services:</p>
<ul class="service-list">
    	<li>File Storage Services</li>

    	<li>Document Storage Services</li>
    	<li>Simple Queue Services</li>
    </ul>
    
<p>You can start writing scalable, highly available, and resilient cloud applications that are portable across all major cloud vendors <i>today</i>.</p>
<p>
Zend has invited the open source community and software vendors of all sizes to participate. IBM, Microsoft, Rackspace, Nirvanix, and GoGrid have already joined the project as contributors. In the coming months, we'll work together to define APIs for these cloud application services, enabling a new generation of cloud native applications written in PHP.
</p>
<p>

    Welcome to a simpler cloud.
</p>
